import PDFDocument from 'pdfkit';
import Contribution from '../models/Contribution.js';
import Loan from '../models/Loan.js';
import MemberLedger from '../models/MemberLedger.js';
import User from '../models/User.js';
import Chama from '../models/Chama.js';
import Cycle from '../models/Cycle.js';
import catchAsync from '../utils/catchAsync.js';
import AppError from '../utils/AppError.js';
import { format } from 'date-fns';

export const generateMemberStatement = catchAsync(async (req, res, next) => {
    const { chamaId, memberId } = req.params;

    // Members can only get their own statement
    if (req.membership.role === 'member' && memberId !== req.user._id.toString()) {
        return next(new AppError('You can only generate your own statement', 403));
    }

    const [chama, member, ledger, contributions, loans] = await Promise.all([
        Chama.findById(chamaId),
        User.findById(memberId),
        MemberLedger.findOne({ chamaId, memberId }),
        Contribution.find({ chamaId, memberId, status: 'verified' }).sort({ paymentDate: 1 }),
        Loan.find({ chamaId, borrowerId: memberId }).sort({ createdAt: -1 })
    ]);

    if (!member) return next(new AppError('Member not found', 404));

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition',
        `attachment; filename="${member.name.replace(/\s/g, '_')}_statement_${format(new Date(), 'yyyy-MM-dd')}.pdf"`
    );
    doc.pipe(res);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text(chama.name, { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Member Statement', { align: 'center' });
    doc.moveDown();
    doc.text(`Member: ${member.name}`, { align: 'left' });
    doc.text(`Generated: ${format(new Date(), 'dd MMM yyyy, HH:mm')}`);
    doc.moveDown();

    // Ledger summary box
    doc.fontSize(14).font('Helvetica-Bold').text('Financial Summary');
    doc.fontSize(11).font('Helvetica');
    doc.text(`Total Contributed: KES ${(ledger?.totalContributed || 0).toLocaleString()}`);
    doc.text(`Total Owed: KES ${(ledger?.totalOwed || 0).toLocaleString()}`);
    doc.text(`Balance: KES ${Math.abs(ledger?.balance || 0).toLocaleString()} ${(ledger?.balance || 0) > 0 ? '(IN ARREARS)' : '(UP TO DATE)'}`);
    doc.moveDown();

    // Contributions table
    doc.fontSize(14).font('Helvetica-Bold').text('Contribution History');
    doc.moveDown(0.5);
    contributions.forEach(c => {
        doc.fontSize(10).font('Helvetica').text(
            `${format(c.paymentDate, 'dd/MM/yyyy')}   KES ${c.amount.toLocaleString()}   Ref: ${c.mpesaRef}`,
            { continued: false }
        );
    });
    doc.moveDown();

    // Loans section
    if (loans.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('Loan History');
        doc.moveDown(0.5);
        loans.forEach(l => {
            doc.fontSize(10).font('Helvetica');
            doc.text(`KES ${l.principalAmount.toLocaleString()} at ${(l.interestRate * 100).toFixed(0)}% flat | Status: ${l.status.toUpperCase()}`);
            doc.text(`Total Due: KES ${l.totalDue.toLocaleString()} | Repaid: KES ${l.totalRepaid.toLocaleString()}`);
            doc.moveDown(0.5);
        });
    }

    // Footer on every page
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).text(
            `Generated by ChamaApp on ${format(new Date(), 'dd MMM yyyy')}. Data accurate as of generation time.`,
            50, doc.page.height - 40, { align: 'center' }
        );
    }

    doc.end();
});
